/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatesDateRouteImport } from './routes/dates.$date'
import { Route as CinemasCinemaIdRouteImport } from './routes/cinemas.$cinemaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesDateRoute = DatesDateRouteImport.update({
  id: '/dates/$date',
  path: '/dates/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemasCinemaIdRoute = CinemasCinemaIdRouteImport.update({
  id: '/cinemas/$cinemaId',
  path: '/cinemas/$cinemaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cinemas/$cinemaId': typeof CinemasCinemaIdRoute
  '/dates/$date': typeof DatesDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cinemas/$cinemaId': typeof CinemasCinemaIdRoute
  '/dates/$date': typeof DatesDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cinemas/$cinemaId': typeof CinemasCinemaIdRoute
  '/dates/$date': typeof DatesDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cinemas/$cinemaId' | '/dates/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cinemas/$cinemaId' | '/dates/$date'
  id: '__root__' | '/' | '/cinemas/$cinemaId' | '/dates/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CinemasCinemaIdRoute: typeof CinemasCinemaIdRoute
  DatesDateRoute: typeof DatesDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates/$date': {
      id: '/dates/$date'
      path: '/dates/$date'
      fullPath: '/dates/$date'
      preLoaderRoute: typeof DatesDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinemas/$cinemaId': {
      id: '/cinemas/$cinemaId'
      path: '/cinemas/$cinemaId'
      fullPath: '/cinemas/$cinemaId'
      preLoaderRoute: typeof CinemasCinemaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CinemasCinemaIdRoute: CinemasCinemaIdRoute,
  DatesDateRoute: DatesDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
